### ISSUE TITLE
DBD::mysql::st execute failed

### ISSUE THREAD

**Issue by sah-anshu** [radetsky/smppd3#2]
Hi

Please advise me about this bug. 
....
          'db-user' => 'root',
          'host' => '0.0.0.0',
          'dsn' => 'DBI:mysql:database=smppd3;host=localhost'
        };

Use of uninitialized value $host in concatenation (.) or string at smppd3.pl line 397.
Use of uninitialized value $port in concatenation (.) or string at smppd3.pl line 397.
DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1 at smppd3.pl line 431.
2015/02/09 17:24:36 Can't execute GET MO statement:  DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1 at smppd3.pl line 431.
DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1 at smppd3.pl line 431.
    ...propagated at smppd3.pl line 434.

Regards
Anshu

**Comment by sah-anshu** [comment]
I installed DBD::mysql

anshu@anshu-lenovo-3000-g530:~/Desktop/proj/websmpp/DBD-mysql-4.029$ sudo make install
Files found in blib/arch: installing files in blib/lib into architecture dependent library tree
Installing /usr/local/lib/perl/5.18.2/auto/DBD/mysql/mysql.so
Installing /usr/local/lib/perl/5.18.2/auto/DBD/mysql/mysql.bs
Installing /usr/local/lib/perl/5.18.2/DBD/README.pod
Installing /usr/local/lib/perl/5.18.2/DBD/mysql.pm
Installing /usr/local/lib/perl/5.18.2/DBD/mysql/GetInfo.pm
Installing /usr/local/lib/perl/5.18.2/DBD/mysql/INSTALL.pod
Installing /usr/local/lib/perl/5.18.2/Bundle/DBD/mysql.pm
Installing /usr/local/man/man3/Bundle::DBD::mysql.3pm
Installing /usr/local/man/man3/DBD::mysql.3pm
Installing /usr/local/man/man3/DBD::README.3pm
Installing /usr/local/man/man3/DBD::mysql::INSTALL.3pm
Appending installation info to /usr/local/lib/perl/5.18.2/perllocal.pod


But still after the same error.

DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1 at smppd3.pl line 432.
2015/02/09 18:09:33 Can't execute GET MO statement:  DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1 at smppd3.pl line 432.
DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1 at smppd3.pl line 432.
	...propagated at smppd3.pl line 435.

**Comment by radetsky** [comment]
Hello, 

smppd3 is unstable right now. It have bug in MO-handler.  
This bug is not fixed right now, so I think you do not have to use it. 

I can help you to install and use it for some commercial interest.  
Of course I'll fix it.

Do you have an interest for this offer ?
